VALID_TRANSITIONS = {
    "created": {"accepted", "cancelled"},
    "accepted": {"planning", "cancelled"},
    "planning": {"internal_review", "cancelled"},
    "internal_review": {"submitted_for_approval", "reworking", "failed", "cancelled"},
    "submitted_for_approval": {"approved", "rejected", "escalated", "cancelled"},
    "rejected": {"reworking", "cancelled"},
    "reworking": {"internal_review", "failed", "cancelled"},
    "approved": {"dispatched", "cancelled"},
    "dispatched": {"executing", "cancelled"},
    "executing": {"reporting", "repair_pending", "paused", "failed", "cancelled", "frozen"},
    "repair_pending": {"repair_authorized", "escalated", "frozen", "cancelled"},
    "repair_authorized": {"rerunning", "cancelled"},
    "rerunning": {"executing", "failed", "paused", "cancelled", "frozen"},
    "reporting": {"archived", "reworking", "escalated", "cancelled"},
    "paused": {"executing", "rerunning", "cancelled", "frozen"},
    "escalated": {"planning", "reworking", "repair_authorized", "cancelled"},
    "failed": {"repair_pending", "reworking", "cancelled", "frozen"},
    "frozen": {"repair_authorized", "cancelled"},
    "archived": set(),
    "cancelled": set(),
}
